### ISSUE TITLE
Add Laravel 10 support to the Open Food Facts package

### ISSUE THREAD

**Issue by khalyomede** [openfoodfacts/openfoodfacts-laravel#39]
### Problem

I want to upgrade to Laravel 10 and the package does not support it.

### Proposed solution

Add support for Laravel 10.

**Comment by fogbreaker** [comment]
bump

**Comment by kaemmi84** [comment]
I also need Laravel 10 support :(

**Comment by mpoweredo** [comment]
bump

**Comment by teolemon** [comment]
Can we merge https://github.com/openfoodfacts/openfoodfacts-php/pull/47 ?

**Comment by teolemon** [comment]
It drops php7 it seems. Is that problematic?

**Comment by epalmans** [comment]
as long as we tag it as a new "major" release (1.x or 0.3.x), then I don't see any problems.

**Comment by teolemon** [comment]
- See also #48
