### ISSUE TITLE
Require a custom user agent to use the SDK

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-laravel#44]
### What
- Require a custom user agent to use the SDK
- Using the SDK and the API in general will remain as of today: free and accessible for everyone.
IN the same way, we don't want to implement an API key mechanism and all that kind of stuff.
- However, due to misuse of the API through various SDKs, we will now force all language clients to have a valid User Agent so that we can reach out in case of problems.
- For now, We will only require an app name for the user agent.

**Comment by Dwarfex** [comment]
@teolemon - what exactly is the misuse? 
I'm afraid simply adding a user agent won't solve any essential misuse - and - would not help in contacting. 

Who do you reach out to on a useragent like e.g. "PHP-SDK - Crawler"?

**Comment by Dwarfex** [comment]
Would't it be better to create personalized (organizational or independent) API keys?

**Comment by epalmans** [comment]
@teolemon this package is already doing this: https://github.com/openfoodfacts/openfoodfacts-laravel/blob/44ee0c288278d683b2bf4f6956e1ed53c337665b/src/OpenFoodFactsApiWrapper.php#L38

**Comment by teolemon** [comment]
@epalmans 
- Do we concatenate a custom part to the Laravel part ?
- Is there a warning if no custom part is added ?

@Dwarfex : for now, just personalized headers.

**Comment by epalmans** [comment]
> * Do we concatenate a custom part to the Laravel part ?

No. Currently, the user-agent value is populated with the _name of the app_ the developer is using the package within. On default laravel installation this is "Laravel". As a fallback the value is set instead "Laravel Open Food Facts - https://github.com/openfoodfacts/openfoodfacts-laravel". However in practice, that latter shouldn't ever happen since the APP_NAME environment variabele is - as far as I am aware - always available and set in Laravel app's. 


> * Is there a warning if no custom part is added ?

No, but it won't happen anyhow. See previous answer.

**Comment by Dwarfex** [comment]
@teolemon 

> what exactly is the misuse?

**Comment by teolemon** [comment]
It's not Laravel SDK specific, we're getting many search queries (and other) that don't make any sense for human usage, and it would be cool to have an idea of who is using the API.

**Comment by epalmans** [comment]
for the SDK's in general we could maybe introduce some kind of custom headers, like X-OFF-SDK (e.g. having a value of Laravel, Android, Ruby, whatever) along with X-OFF-SDK-VERSION to specify the SDK version no.
