### ISSUE TITLE
Cannot install with laravel 11.7

### ISSUE THREAD

**Issue by DrSAS** [openfoodfacts/openfoodfacts-laravel#52]
### What
The installation via composer doesn't work on Laravel 11.7.0

### Steps to reproduce the behavior:
1. `composer require openfoodfacts/openfoodfacts-laravel` on a Laravel project with version `11.7.0`

### Expected behavior
Installing the package with composer :)

### Screenshots
```
Problem 1
    - openfoodfacts/openfoodfacts-laravel[v0.4.0, ..., v0.4.1] require openfoodfacts/openfoodfacts-php ^0.3.0 -> satisfiable by openfoodfacts/openfoodfacts-php[v0.3.0].
    - openfoodfacts/openfoodfacts-laravel v0.1 requires illuminate/support 5.7.x|5.8.x|^6.0|^7.0 -> found illuminate/support[v5.7.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - openfoodfacts/openfoodfacts-laravel[v0.2, ..., v0.2.2] require illuminate/support 5.7.x|5.8.x|^6.0|^7.0|^8.0 -> found illuminate/support[v5.7.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - openfoodfacts/openfoodfacts-laravel v0.3.0 requires illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - openfoodfacts/openfoodfacts-php v0.3.0 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - Root composer.json requires openfoodfacts/openfoodfacts-laravel * -> satisfiable by openfoodfacts/openfoodfacts-laravel[v0.1, ..., v0.4.1].
```

### Platform (Desktop, Mobile, Hunger Games)
 - OS: Debian in Docker container
 - Platform: WSL2 (Debian) on Windows 11, PHP 8.3.8

Thank you!

**Comment by epalmans** [comment]
>  - openfoodfacts/openfoodfacts-php v0.3.0 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.

this might be the issue: The upstream package requires ext-gd, which appears not to be installed on your end

**Comment by DrSAS** [comment]
Hello @epalmans, I've tried to install GD (successfully) but the error still occurs ~(without the GD error line, of course)~. I also tried to install https://github.com/openfoodfacts/openfoodfacts-php repository, which passed, I'm using it in the meantime :)

**Comment by epalmans** [comment]
could you share your composer.json?

**Comment by DrSAS** [comment]
@epalmans I just did another test and finally managed to load the repository. I think GD was the source of the problem. I must have forgotten to restart the service after installation. Sorry about that! 😅
